extends:
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  linebreak-style: 0
  quotes:
    - error
    - single
  no-restricted-syntax: 0
env:
  browser: true
  node: true
  es6: true